---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2
          cache: "pip"

      - name: Install uv
        run: pipx install uv

      - name: Installing dependencies
        run: uv pip install -r requirements-dev.txt --system

      - name: set PY env variables for pre-commit env cache
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{env.PY}}|${{hashFiles('.pre-commit-config.yaml')}}

      - name: Run linters
        run: |
          pre-commit run --all --show-diff-on-failure --color=always

      - name: Run tests
        run: pytest
